services:
  kafka:
    image: docker.io/confluentinc/cp-kafka:7.6.0
    container_name: aegis_kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_KEY_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
      KAFKA_VALUE_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: docker.io/provectuslabs/kafka-ui:latest
    container_name: aegis_kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "aegis-core"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
    depends_on:
      - kafka

  minio:
    image: cgr.dev/chainguard/minio:latest
    container_name: aegis_minio_lake
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "aegis_admin"
      MINIO_ROOT_PASSWORD: "aegis_secure_password"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  clickhouse:
    image: docker.io/clickhouse/clickhouse-server:24.3
    container_name: aegis_clickhouse_dw
    ports:
      - "8123:8123"
      - "9004:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DB: "aegis_analytics"
      CLICKHOUSE_USER: "aegis_user"
      CLICKHOUSE_PASSWORD: "aegis_dw_password"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./packages/db/clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  kafka_data:
  minio_data:
  clickhouse_data: